import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./styles.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <p>Homepage Layout</p>
         <nav className="navbar">
      <ul className="navbar-links">
        <li>
          <Link href="/">Home</Link>
        </li>
        <li>
          <Link href="/blog">Latest Posts</Link>
            </li>
             <li>
          <Link href="/dashboard">Dashboard</Link>
            </li>
              <li>
          <Link href="/about">About</Link>
            </li>
              <li>
          <Link href="/team">Team</Link>
            </li>
             <li>
          <Link href="/about/contact">contact</Link>
        </li>
      </ul>
    </nav>
        
        {children}</body>
    </html>
  );
}
